gText_Birch_Welcome::
	.string "Hi! Sorry to keep you waiting!\p"
	.string "First, let me congratulate you\n"
	.string "on your successful application!\p"
	.string "My name is Professor Birch.\p"
	.string "I will be your instructor and\n"
	.string "mentor in your studies.\p"
	.string "$"

gText_Birch_Pokemon::
	.string "At my lab, we research the\n"
	.string "creatures known as “Pokémon.”\p"
	.string "\n"
	.string "$"

gText_Birch_MainSpeech::
	.string "This world is widely inhabited by\n"
	.string "many different species of Pokémon.\p"
	.string "And we humans live alongside them;\n"
	.string "at times as friendly playmates, and\l"
	.string "at times as cooperative workmates.\p"
	.string "Some people even train with Pokémon\n"
	.string "to battle with others like them.\p"
	.string "But despite our closeness, we don't\n"
	.string "know everything about Pokémon.\p"
	.string "In fact, there are still many\n"
	.string "secrets surrounding Pokémon.\p"
	.string "I've been undertaking my research\n"
	.string "to unravel these Pokémon mysteries.\l"
	.string "And, soon, you will be, too.\p"
	.string "$"

gText_Birch_AndYouAre::
	.string "Let's prepare your Trainer Card.$"

gText_Birch_BoyOrGirl::
	.string "Which of these best represents you?$"

gText_Birch_WhatsYourName::
	.string "Thought so.\p"
	.string "And just to make sure,\n"
	.string "how do you spell your name?$"

gText_Birch_SoItsPlayer::
	.string "So it's {PLAYER}{KUN}?$"

gText_Birch_YourePlayer::
	.string "Wonderful!\p"
	.string "You're {PLAYER}{KUN}, who lives in\n"
	.string "the town of Verdanturf.\l"
	.string "Everything is in order!\p"
	.string "$"

gText_Birch_AreYouReady::
	.string "All right, are you ready?\p"
	.string "Your academic career is about\n"
	.string "to unfold.\p"
	.string "Take courage and leap into the\n"
	.string "world of Pokémon, where dreams,\l"
	.string "adventure, and friendships await!\p"
	.string "Well, I'll be visiting you soon.\n"
	.string "I look forward to meeting you!\p"
	.string "$"
